export const PERMISSIONS = [
  "customers.read.any",
  "customers.create.any",
  "customers.update.any",
  "customers.delete.any",
  "customers.import.any",
  "vendors.read.any",
  "vendors.create.any",
  "vendors.update.any",
  "vendors.delete.any",
  "bookings.read.any",
  "bookings.create.any",
  "bookings.update.any",
  "bookings.delete.any",
  "bookings.status.update.any",
  "payments.read.any",
  "payments.receivable.create.any",
  "payments.expense.create.any",
  "payments.refund.create.any",
  "accounts.read.any",
  "accounts.create.any",
  "accounts.update.any",
  "accounts.delete.any",
  "reports.read.any",
  "reports.export.any",
  "files.read.any",
  "files.upload.any",
  "files.update.any",
  "files.delete.any",
  "files.download.any",
  "ocr.scan.any",
  "audit_logs.read.any",
  "audit_logs.export.any",
  "users.read.any",
  "users.update.any",
  "users.role.update.any",
  "users.status.update.any",
  "metrics.read.any",
  "metrics.reset.any",
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];
